# /config/addons/makemkv_builder/Dockerfile
ARG BUILD_FROM
FROM ${BUILD_FROM}

# Opcjonalnie: Można tu dodać etykiety, jeśli chcesz
# LABEL org.opencontainers.image.authors="matsob0123"
# LABEL org.opencontainers.image.description="MakeMKV addon for Home Assistant"

# Nie trzeba nic więcej robić. Pliki dodatku (run.sh etc.) są dodawane automatycznie.