build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
labels:
  org.opencontainers.image.title: piSignage Server
  org.opencontainers.image.description: Local Server to manage piSignage digital signage players
  org.opencontainers.image.source: https://github.com/colloqi/pisignage-server
  org.opencontainers.image.licenses: AGPL-3.0
args: {}