name: "SpotiFLAC"
version: "1.0.1"
slug: "spotiflac"
description: "Web-based GUI for downloading high-quality FLAC audio from Tidal, Qobuz, and Amazon Music via a browser at https://<your-ha-ip>:3001"
startup: services
boot: auto
host_network: false
apparmor: true
ports:
  3001/tcp: 3001
privileged:
  - SYS_ADMIN
options:
  TZ: "Etc/UTC"
  PUID: 1000
  PGID: 1000
schema:
  TZ: str
  PUID: int
  PGID: int
map:
  - share:rw
arch:
  - amd64
url: https://github.com/matsob0123/hassio-addons
