name: "Eclipse Temurin JDK 21"
version: "1.1"
slug: "temurin_21"
description: "Addon that contains Temurin 21"
startup: services
boot: auto
host_network: true
stdin: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
options:
  WORKDIR: "/config/temurin-21"
  COMMAND: "java -jar example.jar --nogui"
schema:
  WORKDIR: str
  COMMAND: str
arch:
  - amd64
  - aarch64
  - armv7
map:
  - config:rw
