name: xTeVe
version: "2.5.3"
slug: xteve
description: M3U Proxy for Plex DVR and Emby/Jellyfin Live TV
url: https://github.com/matsob0123/hassio-addons
arch:
  - aarch64
  - amd64
startup: services
boot: auto
host_network: false
apparmor: true
webui: "http://[HOST]:[PORT:34400]/web"
ports:
  34400/tcp: 34400
map:
  - config:rw
  - share:rw
