name: "LIMBO Server"
version: "1.3"
slug: "limbo_server"
description: "Uruchamia LIMBO.jar z konfigurowalnymi argumentami i dostępem do plików"
startup: services
boot: auto
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
options:
  ARGS: "--nogui"          # argumenty do uruchomienia JAR
  JAR_PATH: "/config/limbo/limbo.jar"   # ścieżka do JAR na hoście (do mapowania)
  CONFIG_DIR: "/config/limbo"    # folder z configiem
schema:
  ARGS: str
  JAR_PATH: str
  CONFIG_DIR: str
arch:
  - amd64
  - aarch64
  - armv7
