name: "LIMBO Server"
version: "2.0"
slug: "limbo_server"
description: "Dodatek do uruchamiania serwera z własną komendą Java"
startup: services
boot: auto
host_network: true
stdin: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
options:
  WORKDIR: "/config/limbo"
  COMMAND: "java -jar limbo.jar --nogui"
schema:
  WORKDIR: str
  COMMAND: str
arch:
  - amd64
  - aarch64
  - armv7
map:
  - config:rw
