##
## MakeMKV Wrapper — build.yaml
## Used by the Home Assistant build toolchain
##
## ⚠️  PLEASE CHANGE THE VERSION NUMBER IN config.yaml TO HIGHER THAN 2.0.3
##

build_from:
  aarch64: jlesage/makemkv:latest
  amd64:   jlesage/makemkv:latest

squash: false
