name: "Java Runner"
version: "1.1"
slug: "Java_Runner"
description: "Java server."
startup: services
boot: auto
host_network: true
stdin: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
options:
  WORKDIR: "/config/limbo"
  COMMAND: "java -jar limbo.jar --nogui"
  JAVA_VERSION: "21" # <--- New option for Java version
schema:
  WORKDIR: str
  COMMAND: str
  JAVA_VERSION: str # <--- Schema for the new option
arch:
  - amd64
  - aarch64
  - armv7
map:
  - config:rw