name: "Java Runner"
version: "1.1"
slug: "Java_Runner"
description: "Java server."
startup: services
boot: auto
host_network: true
stdin: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
options:
  WORKDIR: "/config/limbo"
  COMMAND: "java -jar limbo.jar --nogui"
  JAVA_VERSION: "21" # Domyślna wersja Javy
schema:
  WORKDIR: str
  COMMAND: str
  JAVA_VERSION: list(str) # Zmieniamy na listę, żeby umożliwić wybór z predefiniowanych opcji
  # Możesz tutaj dodać walidację, np. enum: ["8", "11", "17", "21"]
  # W Home Assistant schema możesz użyć np. "enum": ["8", "11", "17", "21"]
  # (dla prostoty zostawię str, ale enum jest lepsze do listy wyboru)
arch:
  - amd64
  - aarch64
  - armv7
map:
  - config:rw